### ISSUE TITLE
HSL demo is blank

### ISSUE THREAD

**Issue by ThatsNoMoon** [LebsterFace/HDTixy#1]
I was able to reproduce this on firefox and edge. The last demo also uses `hsl(..)` and is also blank, so I'm guessing `hsl` is just causing some error, though I don't see one in the dev tools console.
![image](https://user-images.githubusercontent.com/25443950/108896045-9f876f80-75d1-11eb-894a-26d2ee18366d.png)

**Comment by LebsterFace** [comment]
Thanks, the issue was with the HSL function. It was still using math functions functions without the `Math.` prefix (since I was assigning every property of Math to a global constant instead of doing it just inside the TIXY function)

Fixed in the latest commit
